[package]
name = "buttplug-morse"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.51"
buttplug = "5"
phf = { version = "0.10.0", features = ["macros"] }
tokio = "1.10.0"
