[package]
name = "example"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.16"
tokio = { version = "1.10.0", features = ["macros"] }
buttplug = "5"
buttplug-morse = { path = "../buttplug-morse" }
